In [4]:
import numpy as np

In [5]:
arr = np.arange(0, 30, 3)

In [6]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
arr[2]

6

In [11]:
arr[2:6]

array([ 6,  9, 12, 15])

In [13]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [14]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
arr[:5] += 2

In [18]:
arr

array([ 2,  5,  8, 11, 14, 15, 18, 21, 24, 27])

In [19]:
arr[2:] = 100

In [20]:
arr

array([  2,   5, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr = np.arange(50).reshape((5, 10,))

In [56]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
arr.shape

(5, 10)

In [55]:
arr[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [57]:
arr2 = arr[:3]

In [59]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
arr2[:] = 100

In [62]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [63]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [65]:
arr2 = arr[:3].copy()

In [66]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [67]:
arr2[:] = 200

In [69]:
arr2

array([[200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200, 200, 200, 200, 200]])

In [75]:
arr[2:4, 0:2]

array([[100, 100],
       [ 30,  31]])

In [87]:
bol = arr < 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [88]:
arr[bol]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [89]:
array = np.linspace(0, 100, 30)

In [90]:
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [100]:
array.shape

(30,)

In [101]:
array = array.reshape((5,6,))

In [102]:
array.shape

(5, 6)

In [103]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931],
       [ 20.68965517,  24.13793103,  27.5862069 ,  31.03448276,
         34.48275862,  37.93103448],
       [ 41.37931034,  44.82758621,  48.27586207,  51.72413793,
         55.17241379,  58.62068966],
       [ 62.06896552,  65.51724138,  68.96551724,  72.4137931 ,
         75.86206897,  79.31034483],
       [ 82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [104]:
array = array.round()

In [105]:
array

array([[  0.,   3.,   7.,  10.,  14.,  17.],
       [ 21.,  24.,  28.,  31.,  34.,  38.],
       [ 41.,  45.,  48.,  52.,  55.,  59.],
       [ 62.,  66.,  69.,  72.,  76.,  79.],
       [ 83.,  86.,  90.,  93.,  97., 100.]])

In [115]:
array[:2, :3]

array([[ 0.,  3.,  7.],
       [21., 24., 28.]])

In [114]:
array[1, 2]

28.0