In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

<h2>Arrays no Numpy</h2>

In [13]:
np.array(minha_lista)

array([1, 2, 3])

In [22]:
minha_matriz = [[1,2,3], [4, 5, 6], [7, 8, 9]]

In [30]:
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

<h2>Arange</h2>

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

<h1>Zeros</h2>

In [47]:
zeros = np.zeros(3)

In [49]:
zeros

array([0., 0., 0.])

In [52]:
zeros = np.zeros((3,3,))

In [54]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<h2>Ones</h2>

In [56]:
ones = np.ones(3)

In [57]:
ones

array([1., 1., 1.])

In [58]:
ones = np.ones((2,2,))

In [59]:
ones

array([[1., 1.],
       [1., 1.]])

<h2>Matriz identidade</h2>

In [62]:
identidade = np.eye(5)

In [64]:
identidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<h2>Linspace</h2>

In [80]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

<h2>Random</h2>

In [86]:
np.random.rand()

0.6768012576976531

In [177]:
np.random.rand(5)

array([0.79450556, 0.83331818, 0.7203487 , 0.9836498 , 0.91598101])

In [95]:
np.random.rand(5, 4)

array([[0.26842465, 0.20679248, 0.51903364, 0.52275099],
       [0.53323412, 0.02909795, 0.80302441, 0.24693416],
       [0.80306123, 0.6224915 , 0.37654472, 0.12252738],
       [0.32175529, 0.12571018, 0.32895488, 0.47275643],
       [0.86674986, 0.78729574, 0.0689465 , 0.90550671]])

In [98]:
np.random.rand(5) * 10

array([1.36256721, 7.86734082, 3.08879477, 7.90756691, 8.09275092])

In [103]:
np.random.randn(4)

array([-0.56442595,  0.68452238, -1.2885909 ,  0.25110143])

In [202]:
np.random.randint(0, 5, 10)

array([3, 3, 2, 2, 4, 3, 2, 3, 0, 4])

<h2>Round</h2>

In [201]:
np.round(1.11111, 2)

1.11

In [203]:
np.round(np.random.rand(5)*10, 1)

array([0.1, 0.1, 1.9, 3.9, 5.5])

<h2>Reshape</h2>

In [220]:
arr = np.random.rand(10)

array([0.35844368, 0.99167674, 0.73578667, 0.83635046, 0.79877032,
       0.00415915, 0.14331387, 0.76754345, 0.90882238, 0.24649347])

In [221]:
arr.reshape(2, 5)

array([[0.35844368, 0.99167674, 0.73578667, 0.83635046, 0.79877032],
       [0.00415915, 0.14331387, 0.76754345, 0.90882238, 0.24649347]])

In [227]:
arr = arr.reshape(5, 2)

array([[0.35844368, 0.99167674],
       [0.73578667, 0.83635046],
       [0.79877032, 0.00415915],
       [0.14331387, 0.76754345],
       [0.90882238, 0.24649347]])

In [231]:
arr.shape

(5, 2)

<h2>Max-Min...</h2>

In [230]:
arr.max()

0.9916767429507202

In [233]:
arr.min()

0.004159149606668633

In [235]:
arr.argmax()

1

In [236]:
arr.argmin()

5